import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { motion } from 'framer-motion'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Square Framer Motion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <motion.div
          style={{
            width: 150,
            height: 150,
            borderRadius: 20,
            backgroundColor: "#000080"
          }}
          whileHover={{
            scale: 0.8,
            backgroundColor: "#800000"
          }}
        />
      </main>
    </>
  )
}
